### Default Profile
server:
  port: 8080

spring:
  application:
    name: device-uptime-monitoring
  cloud:
    config:
      fail-fast: true

#below property is used for File database
#kv.datasource.url = F:\\db


---
### Local Profile
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false # Disable Spring Cloud for local profile

## InfluxDb Config
kv:
  influxdb:
    url: "http://influxdb.np.kvhome.in/"
    token: sg2oMb1I6PwTpKh2oIcv5JAe00-ASUS82_WmMmgVOzyjV5Cbzfed45RXZv4tGnsm165gKR5SXnG-dIwForZK-w==

eureka:
  client:
    enabled: false # Disable Eureka for local profile


---
### GKE Profile
spring:
  config:
    activate:
      on-profile: gke
    import: "configserver:http://config-server.kvhome.in"